### ISSUE TITLE
Variations to be displayed during Review

### ISSUE THREAD

**Issue by marek-jasovsky** [ligi/gobandroid#108]
Hi

It would be helpful in review-mode, if in case actual move has more than 1 move-variation following, that those variations are marked with lowercase letters so that when the dialog pops up to select the variation, user can see where those variations go. Option 2 would be to have select-buttons for variations above navigations buttons. so that current pop-up dialog does not have to be shown / tree navigation widget for the variaitons.

Option 1 is already solved at my PC locally, I will try to upload the patch to github.

let's please continue the discussion here.

thanks, Marek

**Comment by icehong** [comment]
I am trying work on this topic in option 2 .
