### ISSUE TITLE
Markings inconsistently appear before or after move

### ISSUE THREAD

**Issue by sligocki** [ligi/gobandroid#138]
SGF markings (like letters or triangles) sometimes appear before the move they are intended to appear on. I think this is a gobandroid bug. Specifically, here's a tiny testcase:

`(;LB[aa:A]TR[ab]W[bd]TR[bb]LB[ba:B];)`

The label A and triangle at ab are displayed before the move. the triangle at bb and the label B appear after. However, I think they should all appear at the same time (I think after the move).

For example, http://www.red-bean.com/sgf/sgf4.html says that "the order of properties in a node is not fixed. It may change every time the file is saved and may vary from application to application. Furthermore applications should not rely on the order of property values. The order of values might change as well."

In this case the node everything between ;s and each property is something of the form: XY[...].

**Comment by ligi** [comment]
A and the first TR belong to virtual move 0 here - I think the current implementation is correct - how otherwise you could mark in the intro-comment - I am closing this for now - but would be open to reconsider when seeing a real-world problem or a documentation that clearly states this case

**Comment by sligocki** [comment]
Hi ligi, sorry that the original post was too vague. Here is a real-world example: http://pastebin.com/2VabHV4u

Go ahead to Move 10 in the main line. On gobandroid it lists 2 As and a B. But on http://eidogo.com/#1rHyeYTpw you can see it correctly only shows the A at R8. Then at Move 11, the other A and B are listed correctly.

The relevant section of SGF in this case is:

```
;W[ol]
LB[ql:A]
C[This and the ...];
LB[cq:A][co:B]
B[cp]
C[Problem:  White to play.  Which is better, White A or B?]
```

Note how there are two section separated by `;` here: `;W[ol]LB[ql:A]C[This and the ...]` and `;LB[cq:A][co:B]B[cp]C[Problem:  ...]`. I believe that the `;` are used to separate each Node in the SGF game tree and so the `LB[ql:A]` should apply to the `W[ol]` move, while the `LB[cq:A][co:B]` labels should apply to the `B[cp]`.

Looking in the code it looks like you aren't splitting by `;`, but instead by `B[]` and `W[]` elements (which are commonly, but not always the first property in a node).

**Comment by sligocki** [comment]
I'm working on a patch for this.
