### ISSUE TITLE
App says "KO!" when you undo and redo the same moves

### ISSUE THREAD

**Issue by sligocki** [ligi/gobandroid#139]
How to reproduce:
1) Make some moves
2) Undo the last 2 (with the arrow, deleting the variations)
3) Re enter the same last 2 moves by hand

Then you get at toast saying it's "KO!" even though it isn't.

I think this is a problem because the last_board and prev_last_board aren't getting updated when you undo a move.

**Comment by ligi** [comment]
fixed in latest versions
