### ISSUE TITLE
Infinite looping during game with AI

### ISSUE THREAD

**Issue by Akon32** [ligi/gobandroid#142]
A few weeks ago I had noted that AI became not responding after a several moves. Today I found an infinite loop in logs:
https://gist.github.com/Akon32/dcfa3bbada700e541a51/119b7042e939d98f306e179ba8fce4bdbf423461 
(my comments are surrounded with ### ). Program is looping until the user interrupts it. This happens every game, usually after 4-6 moves.
This bug affects 2.0.5 in Google Play and current master HEAD (7bffb1d41). Android 4.1.2.

**Comment by Akon32** [comment]
"ac515ce is the first bad commit" - git bisect result.
(warn: bug is sporadic, so may be in other revision)

**Comment by ligi** [comment]
Fixed in 2.0.9
