### ISSUE TITLE
Counting missed a bit

### ISSUE THREAD

**Issue by sligocki** [ligi/gobandroid#143]
I will attach SGF and screenshot. Didn't check if count is wedding, or just picture is messed up

**Comment by sligocki** [comment]
![screenshot_2015-08-21-09-27-54](https://cloud.githubusercontent.com/assets/2762072/9409744/93ef7e3a-47ea-11e5-880a-aa93d7bebb27.png)

**Comment by sligocki** [comment]
(;FF[4]GM[1]AP[gobandroid:0]SZ[19]DT[2015-08-20]PB[Shawn Ligocki]PW[Tim]BR[3k]WR[2k]KM[7.5]RE[B+3.5]
;B[pd]
;W[dq]
;B[cd]
;W[ed]
;B[pq]
;W[qf]
;B[nc]
;W[cc]
;B[qe]
;W[pf]
;B[pk]
;W[nf]
;B[bc]
;W[dc]
;B[be]
;W[hc]
;B[do]
;W[fp]
;B[cq]
;W[cr]
;B[cp]
;W[er]
;B[cl]
;W[mq]
;B[kq]
;W[po]
;B[qp]
;W[no]
;B[hq]
;W[bq]
;B[bp]
;W[br]
;B[dg]
;W[qo]
;B[or]
;W[mr]
;B[ph]
;W[le]
;B[rp]
;W[ro]
;B[lo]
;W[mo]
;B[lp]
;W[nq]
;B[on]
;W[pp]
;B[qr]
;W[mm]
;B[ln]
;W[nk]
;B[nh]
;W[lm]
;B[in]
;W[lh]
;B[qm]
;W[so]
;B[rh]
;W[rr]
C[Oops]
;B[rf]
;W[lc]
;B[fn]
;W[fg]
;B[fi]
;W[rg]
;B[qg]
;W[qc]
;B[rd]
;W[pb]
;B[oc]
;W[rc]
;B[ob]
;W[pa]
;B[sc]
;W[sb]
;B[ra]
;W[sd]
;B[pe]
;W[gh]
;B[hj]
;W[ma]
;B[mb]
;W[lb]
;B[na]
;W[la]
;B[cb]
;W[db]
;B[bb]
;W[ap]
;B[da]
;W[ea]
;B[ca]
;W[eb]
;B[ao]
;W[aq]
;B[bn]
;W[hp]
;B[gq]
;W[ip]
;B[gp]
;W[hl]
;B[jl]
;W[ii]
;B[ij]
;W[ji]
;B[ef]
;W[ff]
;B[ee]
;W[fe]
;B[dd]
;W[fd]
;B[hi]
;W[hh]
;B[mg]
;W[me]
;B[lg]
;W[kg]
;B[fr]
;W[fq]
;B[sm]
;W[jm]
;B[im]
;W[kn]
;B[jn]
;W[km]
;B[ko]
;W[eo]
;B[en]
;W[il]
;B[jk]
;W[hn]
;B[go]
;W[jo]
;B[io]
;W[pj]
;B[qj]
;W[qi]
;B[pi]
;W[rl]
;B[rm]
;W[pl]
;B[ql]
;W[gr]
;B[hr]
;W[fs]
;B[lk]
;W[nm]
;B[lr]
;W[dh]
;B[eh]
;W[gi]
;B[fj]
;W[gj]
;B[mj]
;W[gk]
;B[ho]
;W[ek]
;B[di]
;W[dl]
;B[ck]
;W[ok]
;B[oj]
;W[pm]
;B[ms]
;W[ns]
;B[ls]
;W[nr]
;B[dm]
;W[lq]
;B[jr]
;W[ej]
;B[ei]
;W[fk]
;B[hm]
;W[lf]
;B[of]
;W[mh]
;B[mi]
;W[ng]
;B[oh]
;W[oe]
;B[og]
;W[od]
;B[nd]
;W[ne]
;B[pc]
;W[dj]
;B[cj]
;W[mk]
;B[li]
;W[kh]
;B[ll]
;W[jj]
;B[ik]
;W[gm]
;B[fm]
;W[gl]
;B[el]
;W[eg]
;B[cg]
;W[md]
;B[qn]
;W[pn]
;B[mp]
;W[np]
;B[mn]
;W[nn]
;B[jp]
;W[nj]
;B[ni]
;W[dp]
;B[cn]
;W[fo]
;B[mc]
;W[ml]
;B[hs]
;W[gs]
;B[gn]
;W[dk]
;B[ch]
;W[fl]
;B[em]
;W[kj]
;B[lj]
)

**Comment by sligocki** [comment]
Upper right corner is the issue.

**Comment by ligi** [comment]
Thanks! Just verified & working on a fix

**Comment by ligi** [comment]
Thanks for the detailed report - just uploaded 2.0.8 to beta - this fixes this bug
