### ISSUE TITLE
Some SGF files don't open

### ISSUE THREAD

**Issue by sligocki** [ligi/gobandroid#144]
For example: http://ayd.yunguseng.com/season13/file.php?p1=210&p2=366&tid=357

I open this with Chrome on Android. It downloads as a .SGF file. But then when I click on it, Android says "Can't open file".

And there doesn't seem to be any way to open it from inside gobandroid app either.

**Comment by ildar** [comment]
Just opened this file by tapping on it in a file manager. No problem.
Version 2.1.0 from Play Market.
