### ISSUE TITLE
Display order of review folders

### ISSUE THREAD

**Issue by gthazmatt** [ligi/gobandroid#149]
I really like that this now supports multiple columns, but since the items can vary in height, it's confusing that they are listed from left to right. I would also like to request that directories be listed first before files.

**Comment by ligi** [comment]
Thanks for the feedback! In 2.1.1 the sort-order is changed so that dirs come before files - not yet sure how to change the left-to-right though - I think up-to-down will look even weirder

**Comment by gthazmatt** [comment]
Do you think you could make each file the same height? Maybe always show the review stars?

**Comment by ildar** [comment]
Why?
IMHO current view is quite ok, just needs time to get used to.

**Comment by gthazmatt** [comment]
This is why. I can't find anything.

![column view](http://i.imgur.com/GLF2RtV.png "This is why")
