### ISSUE TITLE
Export part of the board as ascii or UTF8-emoji for copy-pasting into messengers.

### ISSUE THREAD

**Issue by FSMaxB** [ligi/gobandroid#150]
Friends of mine started sending each other Tsumegos via Whatsapp emojis which requires a lot of effort. So I thought: Wouldn't it be nice if one could just export it directly from gobandroid.

![23041448972491062-1061167677](https://cloud.githubusercontent.com/assets/4294942/11500703/18b19f9c-982f-11e5-9f91-ba6761bcc7ba.jpg)

**Comment by ligi** [comment]
nice idea! Do you know if there is an universal emoji for black and white stones?

**Comment by FSMaxB** [comment]
The ones used in the screenshot are `⚪` (U+26AA MEDIUM WHITE CIRCLE), `⚫` (U+26AB MEDIUM BLACK CIRCLE) and `➕` (U+2795 HEAVY PLUS SIGN).

I don't think there is a universal unicode character with the purpose of representing black or white stones, but those two come close I guess.

**Comment by ligi** [comment]
hm - just pasted this into hangouts and it is not working - then I think I fall back to ASCII better

**Comment by FSMaxB** [comment]
Why not both, with the option to choose one or the other.

The problem with ASCII is, that it will look weird when using proportional fonts.

**Comment by ligi** [comment]
I do not really want any whatsapp specific code in my app as I dislike
it - what do you think about sharing as image - would this work for you?

**Comment by FSMaxB** [comment]
It's not whatsapp specific, these are unicode characters, they will work in every messenger that supports them (tested with whatsapp, threema and Signal as well as my email client), the emojis that are provided by the android operating system contain these characters.

But yeah, Images would work as well.

**Comment by ligi** [comment]
ah now I see - but then wouldn't have unicode characters the same problem with looking weird as the  proportional fonts?

**Comment by FSMaxB** [comment]
Theoretically yes, but because those characters are meant to be as high as they're wide, this shouldn't happen in practice for most fonts.

**Comment by FSMaxB** [comment]
Nice! Thank you very much! I'll try it once it's available via F-Droid!

**Comment by ligi** [comment]
Should be on FDroid soon ( via 2.1.5 ) - let me know if it works for you - the main problem I had that I don't know how to display dead stones ( in ASCII I was using W w and B b ) - also the legend is a problem as the problem of proportional fonts kicked in with the first test - doing no legend for now - should be OK for tsumegos

**Comment by FSMaxB** [comment]
This doesn't work. When I chose "As unicode Text" and press OK, it says "Choose how to send the SGF" and that it can't find any app that supports it. This is different from choosing the SGF option though, as this shows me some apps that support it.

Maybe use the clipboard?

**Comment by ligi** [comment]
sorry this was my mistake - when cleaning up the branch after
developing/testing I made a mistake and removed the mime-type so no apps
where found. Fixed in 2.1.6 I just pushed

**Comment by FSMaxB** [comment]
Nice, it works. Again, big thank you.

**Comment by FSMaxB** [comment]
But there still seems to be a problem: Many apps that should be able to receive shared text (including Signal and Whatsapp) weren't listed.

Wouldn't it be possible to just put the text into the clipboard. This way it is compatible with almost every app.

**Comment by ligi** [comment]
Thanks for the update! Please check out version 2.1.8 - using a different mime-type now and signal is now in the list - cannot tell for whats-app - let me know if it works for you. Would prefer this over the clipboard solution.

**Comment by FSMaxB** [comment]
Works like a charm with every messenge I and some of my friends use.

**Comment by ligi** [comment]
great!
