### ISSUE TITLE
DayNight mode

### ISSUE THREAD

**Issue by ligi** [ligi/gobandroid#158]
use the Appcompat 23.2 function so that users can switch between Day/Night/Auto - need a dark board background ( if anyone knows one with a fitting license let me know ) 

context: https://www.reddit.com/r/baduk/comments/4ajdjr/i_did_a_major_material_redesign_to_gobandroid/d11h14e

**Comment by JohnPablok** [comment]
There's a lot of wooden backgrounds here, although the resolution of the free options is a bit lacking but it might work: http://www.textures.com/browse/fine-wood/14119  I really like the attached one.
![woodfine0011_l ash dark](https://cloud.githubusercontent.com/assets/11724846/13819725/1b97e886-eb60-11e5-9626-400ae719e516.jpg)

**Comment by ligi** [comment]
Looks great - is the licensing so that I can use it in a GPL app? Should I paint white lines on it?

**Comment by JohnPablok** [comment]
I think you should be okay using it, they even allow commercial videogames to use the textures. http://www.textures.com/terms_of_use.html In my opinion black lines look better than white.

**Comment by ligi** [comment]
IANAL but this sounds bad:

2.2 You are not permitted to:

f) release the Photos or derivative products with Photos under Open
Source Licences.

**Comment by JohnPablok** [comment]
Mmm, that's right. Maybe you can use it as long as you don't release the image with the source code? Another option is just making the original gobandroid texture a bit darker.

**Comment by ligi** [comment]
I asked them via email

**Comment by ligi** [comment]
there was an (fast) answer:

Hi,

Releasing our images under an Open Source license is not allowed (even
when the images are modified). So that would not be allowed.

Some developers choose to release the images under a separate (closed
source) license, and the code under an Open Source license.

Kind regards,

Marcel
www.textures.com

**Comment by JohnPablok** [comment]
Interesting! So it is possible as long as you don't host the picture on Github? Either way if you need help modifying the original gobandroid image I'll be glad to help.

**Comment by ligi** [comment]
Not hosting the image on github is bad - e.g. as it is a problem for CI-Servers. If you could try to modify the original image that would be great - I am good with Code - not so good with creating graphics

**Comment by JohnPablok** [comment]
Cool, I'm good with graphics and bad with code hehe! Where can I get the original image from?

**Comment by ligi** [comment]
https://github.com/ligi/gobandroid/blob/master/android/src/main/res/drawable/shinkaya.jpg

**Comment by JohnPablok** [comment]
I made two options, "black walnut" and "oak". ![black walnut](https://cloud.githubusercontent.com/assets/11724846/13825547/a13d4dba-eb78-11e5-9393-3da702f669cb.png)
![oak](https://cloud.githubusercontent.com/assets/11724846/13825550/a54ebc9a-eb78-11e5-9ea0-25d2594c51e3.png)

**Comment by ildar** [comment]
ср, 16 мар. 2016 г. в 23:29, John Pablok <notifications@github.com>:

> Interesting! So it is possible as long as you don't host the picture on
> Github? Either way if you need help modifying the original gobandroid image
> I'll be glad to help.
>
Not true. Github can host non-free resources.
OSMand has non-free layout files hosted on Github.
-- 
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by ligi** [comment]
@ildar the problem is not github - the problem are the ToS of the texture provider

**Comment by ligi** [comment]
Some initial experiments with the dark background - this will be a bit more work than I thought
![dark1](https://cloud.githubusercontent.com/assets/111600/13898204/630a2f8c-edca-11e5-91bc-80a06397ac6b.png)
![dark2](https://cloud.githubusercontent.com/assets/111600/13898206/63150fe2-edca-11e5-85c6-b810365e16bf.png)
![dark3](https://cloud.githubusercontent.com/assets/111600/13898205/6313a512-edca-11e5-9667-479f87074de8.png)

**Comment by JohnPablok** [comment]
Wow! Looks great to me! By the way, if you want to make the images darker/lighter o tweak the color a bit just tell me and I'll do it.

**Comment by ligi** [comment]
thanks, but if you say it looks good I would leave it this way. Was a
bit afraid that the contrast black text on dark bg is too little -
thought I have to go white. Also I am not sure about the blue turn
indicator - is really popping on the dark bg

**Comment by JohnPablok** [comment]
The blue turn indicator could be made Red in dark mode but only if it isn't a hassle to code, it doesn't look bad. I think the contrast with the background is good but I might edit the image a bit tomorrow, a bit less reddish and a bit lighter.

**Comment by JohnPablok** [comment]
In case you want it here's the background just a bit lighter and a bit less red.

![black walnut](https://cloud.githubusercontent.com/assets/11724846/13905014/0e8a725a-ee79-11e5-9b59-ae6c10b23357.png)

**Comment by ligi** [comment]
So this is getting further - might use white font after-all - gives more consistency in night mode

![dark1](https://cloud.githubusercontent.com/assets/111600/13973340/2bf065a4-f0a2-11e5-98be-78857815e8fc.png)
![dark2](https://cloud.githubusercontent.com/assets/111600/13973342/2bf97a2c-f0a2-11e5-8ddd-73fdeaf1fd86.png)
![device-2016-03-23-024957](https://cloud.githubusercontent.com/assets/111600/13973341/2bf7ee1e-f0a2-11e5-8bfa-36926120a49e.png)

**Comment by ligi** [comment]
Version 2.3.2 ( now in beta ) has initial day/night-mode support - feedback welcome

**Comment by JohnPablok** [comment]
Yay! Looks awesome in the pics, although for some reason it is crashing in both my Moto G and my galaxy note 10.1 tablet when selecting the Night option in the settings.

**Comment by ligi** [comment]
Thanks - the minify process seems to have removed the resource for night - I will search for a way to protect it and file aug in the android bugtracker

**Comment by ligi** [comment]
I uploaded 2.3.3 to beta - should work now

**Comment by JohnPablok** [comment]
Looks great! Although I have to agree on what you said previously. The board lines are a bit difficult to discern, but mainly because they are only 1 pixel thin. Maybe the updated image could work (it is a bit lighter) 
![black walnut](https://cloud.githubusercontent.com/assets/11724846/14004625/17805884-f121-11e5-8b57-a396f18ab4e9.png)

**Comment by ligi** [comment]
Using this image for night in 2.3.4

**Comment by ligi** [comment]
btw as I have someone with gfx skills here - it would be super awesome to get replacements for these 2 images which I amateurish clicked together with gimp. But they are for a lot of people the first and maybe only contact to gobandroid as these are the play feature graphics:

![promo_180x120_hd3](https://cloud.githubusercontent.com/assets/111600/14016967/037e0a72-f1c4-11e5-9a9d-d2126cd1a0e3.png)
![promo_1024x500_hd_v3](https://cloud.githubusercontent.com/assets/111600/14016968/03834712-f1c4-11e5-85de-9c7201836162.png)

**Comment by JohnPablok** [comment]
I actually like those images! But I'll see if I can come up with something better :smiley:
