### ISSUE TITLE
Setting to have thicker lines for recording purposes

### ISSUE THREAD

**Issue by ligi** [ligi/gobandroid#159]
The small lines look good on devices but bad on screenshots and recording where compression kicks in. In the settings make a option thick/thin lines to have better recording results

**Comment by ildar** [comment]
that's not a compression. It is resize that makes 1pt lines invisible.
You may try keeping the original size then all lines should persist.

**Comment by ligi** [comment]
It is both - compression and resize - and I cannot control compression/size everywhere - so I think your comment is invalid and this is still needed

**Comment by ildar** [comment]
OK, sorry to bother.
-- 
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/
