### ISSUE TITLE
Undesired sounds

### ISSUE THREAD

**Issue by ildar** [ligi/gobandroid#163]
I have sounds off in settings.
But in review mode I sometimes hear sounds of stone produced.
Please check.
Also it would be nice if the system silent mode be respected.

**Comment by icehong** [comment]
On a fresh install environment , the default  is sound on,  and  checkbox was not checked  in preference view. 
It necessary to set  play sound checkbox default checked to avoid misunderstanding.  . @ligi

**Comment by ligi** [comment]
ah only on fresh installment - thats why I could not reproduce ;-)
Thanks for the investigation!

**Comment by ligi** [comment]
extracted #172

**Comment by ligi** [comment]
fixed in 2.3.8
