### ISSUE TITLE
[FR] make option to change some buttons' behavior

### ISSUE THREAD

**Issue by ildar** [ligi/gobandroid#164]
I wish that in review mode the "beginning" and the "end" buttons (i.e. buttons #1 and #4) could work differently: going to the closest junction point to the left and right from the current move.
This feature could be opt-in in options.

**Comment by ligi** [comment]
you mean to the next/previous move with a variation?

**Comment by ildar** [comment]
No, I mean the 1st and 4th buttons (of 6) which are "start" and "end"
So that the buttons would bring me to the start and the end of the current
variation

**Comment by ligi** [comment]
I don't get it

**Comment by ildar** [comment]
Well,
the 1st button in the review mode brings you to the move 0 - the start of
the game. I suggest an option for this button to bring user to the point
where variations are (junction point) and user can choose another variation
to look through.

**Comment by ligi** [comment]
Ah now finally I got it - good Idea - will do this

**Comment by ligi** [comment]
OK I implemented it this way now - long-press on the buttons is the old behavior - will upload it to beta soon - not yet sure if it should be a setting or not

**Comment by ildar** [comment]
Thanks, I'll test it!
>
> --
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by ligi** [comment]
2.3.9 which is now in beta supports this feature

**Comment by ildar** [comment]
Great! Thanks! Will test it soon.

**Comment by ildar** [comment]
Works great, thanks!
