### ISSUE TITLE
Undoing a pass crash

### ISSUE THREAD

**Issue by ligi** [ligi/gobandroid#191]
Reproduce:
1) Pass
2) undo move
3) move

thanks to rory renton for reporting so nicely with steps!

**Comment by ligi** [comment]
Yea - feel free to do so - no promises on  fast implementation though ..

On 7 December 2016 3:39:49 AM GMT+01:00, smellymoo <notifications@github.com> wrote:
>I know the pain of trying to debug from vague reports like: "it went
>fuzzy, please fix!!1!"
>
>I have some feature suggestions, shall I make issues?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ligi/gobandroid/issues/191#issuecomment-265339065

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by smellymoo** [comment]
Lol, yeah I hear ya ;).
