### ISSUE TITLE
Reviewing games is very slow

### ISSUE THREAD

**Issue by gthazmatt** [ligi/gobandroid#194]
Situation: open an sgf (take one of the monster sgfs, for example), jump to the end, and try to step back through the game. On my Galaxy S6, this is no problem, but on my $40 Kingston tablet (which I bought solely for the purpose of recording games), it can take more than 10 seconds to go back one move. Running the app in an emulator performs about the same.

Now, I've actually been working on this for a bit, and I hope to have a pull request ready in the next day or two.

**Comment by ligi** [comment]
Sounds great - looking forward to the PR! Don't have much time for gobandroid currently - but will review the PR most likely merge.

**Comment by ligi** [comment]
closing as the pr is merged - thanks again!
