### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [ligi/gobandroid#204]
Hi @ligi 

I found [this app ](https://play.google.com/store/apps/details?id=com.qyihumaster.game.go) on Google Play Store. This guys just took the source code, added some ads and put it on the Google Play Store...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay), if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GPL3 and this guy is violating it by distributing the app without the source code;
* He is falsely claiming he made the app;
* Also tell them that this guy has done the same thing already with other apps. Probably this is worth mentioning. (I watch him)

**Comment by ligi** [comment]
Thanks for letting me know!

**Comment by Poussinou** [comment]
@ligi Any news about this GPLv3 violation?

**Comment by ligi** [comment]
Sorry but I did not really have time to follow-up on that. There are also only so little downloads on this app that this was not high priority for me. Gave him a one-star with a comment though ..

**Comment by Poussinou** [comment]
OK

**Comment by Poussinou** [comment]
The app is down, I'm closing this Issue.

Please report it here if you find other copycats in the future.
