### ISSUE TITLE
incorrect answer on tsumego

### ISSUE THREAD

**Issue by skyer9** [ligi/gobandroid#205]
incorrect answer on tsumego

tsumego ggg-easy-07 suggest incorrect answer.
ggg-hard-09 is also incorrect

**Comment by ildar** [comment]
Tsumegos taken from https://github.com/gogameguru/go-problems/ , could you
check the sgf there and report there?

**Comment by skyer9** [comment]
yes. source sgf file is incorrect.
i will issue that site and check answer corrected.

**Comment by ligi** [comment]
should be fixed
