### ISSUE TITLE
bug found while trying to switch to Fullscreen Board on Gobandroid

### ISSUE THREAD

**Issue by tykees** [ligi/gobandroid#210]
#### Expected behavior
I was expecting to see a full-screen board of the game, meaning the board of the game should zoomed out and get more bigger

#### Actual behavior
When i click on full-screen board their was no effect on the screen, the screen size remain stagnant 

#### How to reproduce
1. Download [Gobandroid](https://play.google.com/store/apps/details?id=org.ligi.gobandroid_hd)

2.Launch, click on options located at the upper left of the screen

3. Click on settings and switch `Fullscreen Board`

* Device used: Tecno Droid-pad 8ll
* Operating system: Android version 5.1
*  App version: 2.5.7 

#### Recording Of The Bug
   https://www.youtube.com/watch?v=NI_HXchsCTA

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tykee/bug-found-while-trying-to-switch-to-fullscreen-board-on-gobandroid">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ligi** [comment]
I see the effect - in fullscreen you do not have the status-bar (top) anymore. Not that big of a difference on this device - but this is what fullscreen is doing.
